export const UPDATE_ADMIN_LIST = 'UPDATE_ADMIN_LIST';
export const UPDATE_TYPE_LIST = 'UPDATE_TYPE_LIST';
export const UPDATE_ARTICLE_LIST = 'UPDATE_ARTICLE_LIST';
export const UPDATE_ARTICLE_CONTENT = 'UPDATE_ARTICLE_CONTETN';
export const UPDATE_THUMBNAILS = 'UPDATE_THUMBNAILS';
